---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-static-net
  namespace: network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "macvlan-static-net",
      "type": "macvlan",
      "master": "eth0",
      "capabilities": { "ips": true, "mac": true },
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.0.0/21",
        "rangeStart": "192.168.5.100",
        "rangeEnd": "192.168.5.255",
        "routes": [
          { "dst": "192.168.0.0/16" }
        ],
        "gateway": "192.168.0.1"
      }
    }