# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:U5mN8vZhA3ZPl3TjvC9mmgPHYveQ6EnTnrUUXY3uGR8VyV2UryxIHQ==,iv:88vu3QOXgxZr8MVQ1Mg0V/xPxQEFyHUJo86UbPp1B6Y=,tag:wr/DCrJb8Kyck269IayRug==,type:str]
sops:
  age:
    - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZDZTeUFUWHJScGdaWW5G
        WFJlbkNobk01SktTOVlVbEJLeVROVXJkRkdRCkY2NEF5dU5kRWZjRGN0cW5GdW1R
        UnV3cFZPVU1XaE9aTEJOcEVFalhVU0kKLS0tIDNZR3dhTk5UMHFnSStoWEFhbnl2
        bCtMTGhEeFlZd3dpUXVqVVA3LzRKeWcK7rmVnC/mwzkDuV2O8SUrtLjaOPLtyKNY
        clRVlmrinqPVHaUlxr1nYkZScp7y4BdN7BhFhHvXtr9ZPB0IgFKybg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T10:51:16Z"
  mac: ENC[AES256_GCM,data:grLlT3xGGIJF4x/D/rnFgI2jDED8a8oNvM82K/zLTEqBYkKUoMmyRpDojjsUuhZkPnLdr9RwVZhvnbezYmjbGm31c4s15f08GITyowluV6TMWxbUuoHtOzdgiXoVKaySrW529O10XpnyHXA21eOzXcsGQhjW2Mi67UegEcRToJc=,iv:7YA/ZYZJVRYOaHbwn9GiTb7tk5oXrZd4rT321LSq7rg=,tag:4cqT0tdLN/I8KPcgRLio1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
