# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:zC+yp3GgSzGToLsobVfZLvY8zCjIzVIU+mn4iuXf0AU=,iv:EQsDCPMXCc6FDEHwCOv7UsmpiNXJnMuheorvU2IcTFQ=,tag:ZRZQlWlk9/lq2SVkL3kPgQ==,type:str]
sops:
  age:
    - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybUJiSHNqakpZWHdXN1ZB
        WFNEL0tPWEF5NHBpblJKdDlTdEpoY3NsUFI4CjhsWng2cWxGNTBLRGdseFZ2Q0tO
        ZGI4dDFNYk43clNIVmxqZVI3SjgycncKLS0tIHFwZDkwU3daZFRzbWVWbVJaeUxL
        bjFxejFnc3UxZlFXUythYlYyUWZYdk0Kc2ej0MVHaUjEP5k38JRzGeUV5ty+XW8y
        KHPff+X0jasAVyaW8qq24uEhnIcPZD58xLeHNXq/u6BlXEuG1/76Bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T10:51:16Z"
  mac: ENC[AES256_GCM,data:e5pqe3s1QVoubRzVo0OZIBkjcWa+WoVHJ5vmxfJiDi6h53BOajxTcwCHQFS42xVt2mDhtzWRPgLFnV6vJsr1OtI+x/9dfp0sRIv+Y1SILlDTPfTpNEo5J0RPrwkzR8518legfRIQCwjGdopdfGYE5dzzYh2AsJbWUJ5whPzd3GA=,iv:EFY5IeJBZjfK6fKw0GbdY3srCfXLFpEux2/e+3X+hiQ=,tag:bQ/F6EduqcUS2+7DFRMo9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
