---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-multus
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: multus
      namespace: kube-system
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: network-attachment-definitions.k8s.cni.cncf.io
  interval: 30m
  path: "./kubernetes/apps/kube-system/multus/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: &ns kube-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-multus-networks
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/apps/kube-system/multus/networks"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  wait: true