# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:CVnVelx5YCvxsKliN/W1qEpwvp51zYeD+4zl0k7z9cD7q7iP50SoE2/duC4DGPsaMZJAGqJALhkjKK+tahLo76NGLgUR0H7C1CIfXypq/85Or9dGgptRraIxW7oFGDpOlLQETssPn5JBdmIuIWZ2ZwFfPojSGYkJTC1NB+H9Zqxk7PYX2BdwXKGtGMZFOY9bDnw8szt4OL5z75CbjCiEMAlJuvkOEk9rflpwMRWvJOjc/AvX,iv:DnSGriaXdPRUfdfdOkTM+OOBo3gau5Jku8fjVT2wDHo=,tag:d6D1Jb8Qf4YmuttWXR9R1g==,type:str]
sops:
  age:
    - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZkUyQUQ0cjBLcC9kZ1h2
        bWFONFpGL0FxNURzOVVRK3lOWmE2a0EvUms0Ck9Cak1xL0V2VWJmVlpUMHVLZHJO
        VHpDOHRmbGxDVG5rU2c0ZTFBK1AvWE0KLS0tIFIrbXhOOCtNQWhPdFNQa2hWYzc4
        Rk1BNHUvamVnQnh2dWU1SmJVdXZMcXMK5iCn4lu9rXWzdevunCSDe/Dj4DSKFk4c
        1mgbP0vboHhgp5X3q6ASLtUY3+Y8LYtbeK3U1vtPGW6NyJwCBoZMCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T10:51:16Z"
  mac: ENC[AES256_GCM,data:3GMj5njFWSHIA11xT0Fw921m9f4Rm7JS1jZSaR0uE8hZ2xnjmrtKFEpUaAEc6VvB2KjhJj+sz1UL7/U8RsSBDDiDobWsFdcDmsbMs869SUZ4U3MfxHtJCRqbkjmAmmWpORriwEwvY8RJn8pwmZUkpR96JpzINhuOG0MnpQkFjWs=,iv:UEqTIUiagNt21eCF9yf81LJAfeD09z6COtXO5ySKQBY=,tag:46O0T/OLKf51P+sr5nOxkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
