# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:xvuIg14kd58Ghf+kzv91WnNvL1H1EjTBRJDLTgjGOvDttbrr4E63Rw==,iv:8IWx6Z7pieAnAiTzv7w9xM8BS9xBIvgUwfJKjVvbJs4=,tag:5YEmkfLFQqGSh5UnY8mZpA==,type:str]
sops:
  age:
    - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRUNvYjRyZEg5dFlBQ2pU
        cnZwTkQ2VE9Oa2l6ekFNc01zbG42UzVDYVN3Cmo3c2cxeGE4VDYvRmpCd0tSTVo3
        dHN3QlZ3aGtxdkJnL0dMd2JGUzV3V0UKLS0tIEtIN0NBcE5Ld1FlcjBHUnJoWXNx
        dDZNQzh4M3RTalhpUzlncEY3MVVDSVEKOuX1kYMWsG0Q7x102ODRbg2Gm6T71Im0
        c3EYAbEvoCan4vFo0VQn2KDzcav9RZhcvw78dVByYwHTuWrWfHbWTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T10:51:16Z"
  mac: ENC[AES256_GCM,data:ALNyBnwbqH2NsqrPZyjAzO27HxILzD+NN8l0qBQWIpyqRMT1jL6qacgISAbtW9YszM0kB66aIwX2Po1+p8LiSacE+fFaOmSnpz5jQ6VtV9jrN72Kc99/wmZfd/3SCuF3tIhfcEEhWAWeFApfQgbpBuTNZo3XCrFjEeiuCb34rrU=,iv:QefLwwUzrMtP3bctfvpJmV47KvxVtlSdaoZMn34tTcA=,tag:rCbRQkJgqisITSxIAHqO/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
