apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:o++kQIzY1Eq0U8E=,iv:deqyEdX+jA1kDqJuW24NYxt04b3yY6mfJY5tTkbxFcg=,tag:ri7pSqHdm/WwLXW2eubIGA==,type:str]
sops:
  age:
    - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYzlHdWNpanI1Qkc3R1RQ
        MkZMSzhYWTZENFl4cXJ1TmFEZTR3OGlvM2hFCnNiTE9lMjUrTi9iNkU4dXVxemZX
        RENQalRuTFlET2NjeUV5aHArMzBvNUUKLS0tIHZDNHJaYnlYbWUrSGsvZ2UvZUYx
        b2cyR2JKMkJlMlhsUVVacThqYURsUmcKJxnpYqDFmjt1VZ4eY8dkUyWsZ1oKotNN
        RJFpT9OjIZJThvDQlIRyApSwZGTvTHtonxqCaVH6iKPz9H4IFi5nzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T10:51:16Z"
  mac: ENC[AES256_GCM,data:wo0+fua9sbsWe+w4TcmzIK7PZhFhc5xeG6o1N/kxARj7lvm8KpGqi2H/UaLmJcxRz54oZP4agaB9lYyNrHAHVlDokuvpFPz/jxWHn4YAJZb7hIPvq+MKPHj7DdqnyZKP0II31z4pCwcPJ+zjpO9sJdG0bos5VPnXSCOH3XJLyBM=,iv:2pLRII+0i4DtGxgZnwGqka6+ppbK+nWg+GUG/IQIebg=,tag:NZZ2bpHboOibEKXhymSOnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
